[package]
name = "solana-liq-pool"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
borsh-derive = "1.5.7"
spl-token = { version = "6.0.0", features = ["no-entrypoint"] }
num = "0.4"

[lib]
crate-type = ["cdylib", "lib"]